### ISSUE TITLE
Corrigir bug no método de verificar se a palavra é plural

### ISSUE THREAD

**Issue by bartier** [bartier/safadeza-generator#15]
Estava gerando uma listagem de frases e em alguns casos o script não consegue ser terminado por conta do erro abaixo:

```
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    main()
  File "/home/vitor/.local/share/virtualenvs/safadeza-generator-hEbHoMHa/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/vitor/.local/share/virtualenvs/safadeza-generator-hEbHoMHa/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/vitor/.local/share/virtualenvs/safadeza-generator-hEbHoMHa/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vitor/.local/share/virtualenvs/safadeza-generator-hEbHoMHa/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 90, in main
    frase = gerar_frase(palavra_escolhida, verbo_escolhido)
  File "main.py", line 18, in gerar_frase
    artigo += 's' if eh_plural(resultado_dicio) else ''
  File "main.py", line 45, in eh_plural
    return resultado_dicio.extra.get('Singular') is not None
AttributeError: 'NoneType' object has no attribute 'extra'
```

Provavelmente alguma verificação deve ser levada em conta no método, no entanto o importante a se descobrir é a causa raiz que causa 'NoneType' no objeto `resultado_dicio`, não cheguei a me aprofundar muito nessa questão.

Quem quiser sinta-se à vontade para investigar/aplicar um fix =)

**Comment by luchiago** [comment]
Olá, posso trabalhar nisso ?

**Comment by bartier** [comment]
@luchiago Pode sim!

**Comment by luchiago** [comment]
Resolvido com #17
